export const defaultServices = [
  {
    id: 's1',
    name: 'ACP 3D Facade Cladding',
    slug: 'acp-3d-facade-cladding',
    shortDescription: 'Modern three-dimensional ACP facade cladding for distinctive building exteriors.',
    description: 'We design and install durable ACP 3D facade systems that create bold architectural depth, clean detailing, and a distinctive exterior finish.',
    icon: 'Building2',
    coverImage: '/images/services/acp-3d-facade-cladding.jpg',
    active: true,
  },
  {
    id: 's2',
    name: 'Premium Architectural Elevations',
    slug: 'premium-architectural-elevations',
    shortDescription: 'High-quality architectural elevation solutions for commercial and residential properties.',
    description: 'We create refined architectural elevations using coordinated cladding, glazing, aluminium, and decorative finishes tailored to each building.',
    icon: 'Building',
    coverImage: '/images/services/premium-architectural-elevations.jpg',
    active: true,
  },
  {
    id: 's3',
    name: 'CNC Cut ACP Designs',
    slug: 'cnc-cut-acp-designs',
    shortDescription: 'Precision CNC-cut ACP patterns for custom facades, screens, and feature panels.',
    description: 'Our CNC cutting service produces accurate decorative ACP designs, screens, and patterned panels for memorable architectural details.',
    icon: 'Grid2x2',
    coverImage: '/images/services/cnc-cut-acp-designs.jpg',
    active: true,
  },
  {
    id: 's4',
    name: 'Laser Cut Decorative Panels',
    slug: 'laser-cut-decorative-panels',
    shortDescription: 'Decorative laser-cut panels for elegant screens, partitions, and facade accents.',
    description: 'We deliver custom laser-cut decorative panels with precise patterns for interior partitions, exterior screens, balconies, and feature walls.',
    icon: 'Sparkles',
    coverImage: '/images/services/laser-cut-decorative-panels.jpg',
    active: true,
  },
  {
    id: 's5',
    name: 'Perforated ACP Facades',
    slug: 'perforated-acp-facades',
    shortDescription: 'Ventilated and visually striking perforated ACP facade installations.',
    description: 'Perforated ACP panels provide shade, ventilation, and contemporary visual texture while protecting the building envelope.',
    icon: 'PanelsTopLeft',
    coverImage: '/images/services/perforated-acp-facades.jpg',
    active: true,
  },
  {
    id: 's6',
    name: 'Aluminium Composite Panel Works',
    slug: 'aluminium-composite-panel-works',
    shortDescription: 'Complete ACP fabrication and installation for durable, polished building exteriors.',
    description: 'From design and fabrication to installation, we deliver weather-resistant aluminium composite panel works with clean joints and lasting finishes.',
    icon: 'Layers',
    coverImage: '/images/services/aluminium-composite-panel-works.jpg',
    active: true,
  },
  {
    id: 's7',
    name: 'Glass Glazing',
    slug: 'glass-glazing',
    shortDescription: 'Reliable glass glazing for doors, windows, facades, partitions, and architectural features.',
    description: 'We install high-quality glass glazing systems selected for safety, performance, daylight, and a clean modern appearance.',
    icon: 'DoorOpen',
    coverImage: '/images/services/glass-glazing.jpg',
    active: true,
  },
  {
    id: 's8',
    name: 'Spider Glazing',
    slug: 'spider-glazing',
    shortDescription: 'Frameless point-fixed spider glazing for transparent and elegant facades.',
    description: 'Spider glazing combines structural glass and point-fixed fittings to create bright, open elevations for entrances, atriums, and feature walls.',
    icon: 'Sparkles',
    coverImage: '/images/services/spider-glazing.jpg',
    active: true,
  },
  {
    id: 's9',
    name: 'Structural Glazing',
    slug: 'structural-glazing',
    shortDescription: 'High-performance structural glazing for seamless commercial and residential elevations.',
    description: 'Our structural glazing systems use engineered glass and tested sealants to deliver weather resistance, safety, and uninterrupted facade lines.',
    icon: 'ShieldCheck',
    coverImage: '/images/services/structural-glazing.jpg',
    active: true,
  },
  {
    id: 's10',
    name: 'Aluminium & uPVC Windows',
    slug: 'aluminium-upvc-windows',
    shortDescription: 'Efficient aluminium and uPVC windows designed for comfort, durability, and style.',
    description: 'We supply and install durable aluminium and uPVC window systems with dependable operation, thermal performance, and low maintenance.',
    icon: 'Home',
    coverImage: '/images/services/aluminium-upvc-windows.jpg',
    active: true,
  },
  {
    id: 's11',
    name: 'Exterior Renovation Works',
    slug: 'exterior-renovation-works',
    shortDescription: 'Exterior renovation and facade upgrades that refresh and protect existing buildings.',
    description: 'We transform aging exteriors with carefully planned renovation works, new cladding, glazing, repairs, and coordinated architectural finishes.',
    icon: 'Hammer',
    coverImage: '/images/services/exterior-renovation-works.jpg',
    active: true,
  },
]

export const defaultProjects = [
  {
    id: 'p7',
    name: 'MyCure Hospitals',
    slug: 'mycure-hospitals',
    location: 'Maharanipeta',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    address: 'Gokhale Road, near Jagadamba Junction, Maharanipeta',
    clientName: 'MyCure Hospitals',
    completionDate: '',
    shortDescription: 'Commercial healthcare facade featuring modern architectural cladding and glazing.',
    fullDescription: 'SV Infra projects 972 completed facade and architectural finishing works for the MyCure Hospitals building, a multispecialty healthcare facility serving Andhra Pradesh and Telangana.',
    coverImage: '/images/projects/mycure-hospitals.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p8',
    name: 'Value Zone Hyper Mart',
    slug: 'value-zone-hyper-mart',
    location: 'Storefront location',
    district: 'Not specified',
    state: 'Andhra Pradesh',
    address: 'Exact street address to be added',
    clientName: 'Value Zone Hyper Mart',
    completionDate: '',
    shortDescription: 'Retail storefront facade for Value Zone Hyper Mart, featuring its savings-focused frontage.',
    fullDescription: 'Facade and storefront finishing works for Value Zone Hyper Mart, a large-format retail destination with grocery, household, lifestyle, and promotional retail sections.',
    coverImage: '/images/projects/value-zone-hyper-mart.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p9',
    name: 'Intell Engineering College',
    slug: 'intell-engineering-college',
    location: 'Akkampalli Cross, Kalyandurg Road',
    district: 'Anantapur',
    state: 'Andhra Pradesh',
    address: 'Akkampalli Cross, Kalyandurg Road, PIN 515004',
    clientName: 'Intell Engineering College',
    completionDate: '',
    shortDescription: 'Institutional building facade and entrance signage at the former engineering college campus.',
    fullDescription: 'Architectural facade work for the Intell Engineering College entrance building at Akkampalli Cross on Kalyandurg Road, Anantapur District.',
    coverImage: '/images/projects/intell-engineering-college.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p10',
    name: 'Keshav Grand Hotel & Banquet',
    slug: 'keshav-grand-hotel-banquet',
    location: 'Mahaveer Colony, Kalluru',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    address: 'Near NH 44, Mahaveer Colony, Kalluru, PIN 518003',
    clientName: 'Keshav Grand Hotel & Banquet',
    completionDate: '',
    shortDescription: 'Hotel and convention venue facade along NH 44 with multi-level hospitality spaces.',
    fullDescription: 'Facade and architectural finishing works for Keshav Grand Hotel & Banquet, a hospitality and convention venue with deluxe rooms, banquet halls, and event spaces near NH 44.',
    coverImage: '/images/projects/keshav-grand-hotel-banquet.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p11',
    name: 'LML World - PV Chowdary Motors',
    slug: 'lml-world-pv-chowdary-motors',
    location: 'Dealership facility',
    district: 'Anantapur',
    state: 'Andhra Pradesh',
    address: 'Exact street address to be added',
    clientName: 'P V Chowdary Motors',
    completionDate: '',
    shortDescription: 'Authorized LML World dealership facility for two-wheeler sales, service, and spares.',
    fullDescription: 'Commercial dealership facade for P V Chowdary Motors, an authorized LML World 3S facility handling sales, services, and spares.',
    coverImage: '/images/projects/lml-world-pv-chowdary-motors.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p12',
    name: 'Lodge Building Facade',
    slug: 'lodge-building-facade',
    location: 'Lodge property',
    district: 'Not specified',
    state: 'Andhra Pradesh',
    address: 'Exact street address to be added',
    clientName: 'Lodge Project',
    completionDate: '',
    shortDescription: 'Hospitality property facade with practical, durable exterior finishing.',
    fullDescription: 'Facade and exterior finishing works for a lodge building, balancing a welcoming hospitality frontage with durable materials and clean architectural detailing.',
    coverImage: '/images/projects/lodge-building-facade.jpg',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
]

export const defaultHeroSlides = [
  {
    id: 'h1',
    title: 'Architectural Glazing & Façade Excellence',
    subheading: 'Engineered for Durability, Aesthetic Perfection, and Energy Efficiency',
    buttonText: 'Explore Projects',
    buttonLink: '/projects',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
  {
    id: 'h2',
    title: 'Modern Aluminium & Glass Solutions',
    subheading: 'Premium Structural Glazing, ACP Cladding, and Customized Finishing',
    buttonText: 'Our Services',
    buttonLink: '/services',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
  {
    id: 'h3',
    title: 'Turnkey Commercial & Residential Fit-Outs',
    subheading: 'Delivering High-Quality Architectural Finishing Across AP & Telangana',
    buttonText: 'Get Free Quote',
    buttonLink: '/contact',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
]

export const defaultTestimonials = [
  {
    id: 't1',
    customerName: 'Rajesh Reddy',
    location: 'Hyderabad',
    rating: 5,
    review: 'SV Infra projects 972 completed our office building façade glazing ahead of schedule. The quality of aluminium sections and glass fitting is top notch!',
    status: 'approved',
  },
  {
    id: 't2',
    customerName: 'K. Suresh Kumar',
    location: 'Visakhapatnam',
    rating: 5,
    review: 'Outstanding professionalism. Their team handled our villa glazing and ACP cladding with extreme precision and premium materials.',
    status: 'approved',
  },
  {
    id: 't3',
    customerName: 'Priya Sharma',
    location: 'Vijayawada',
    rating: 5,
    review: 'Very reliable team for interior glass partitioning and customized finishing. Prompt communication and excellent post-installation support.',
    status: 'approved',
  },
]

export const defaultGallery = [
  { id: 'g1', url: '/images/gallery/Image2.jpeg', title: 'Residential Louver Facade', categoryId: 'gcat-facade' },
  { id: 'g2', url: '/images/gallery/Image3.jpeg', title: 'Commercial ACP Building', categoryId: 'gcat-facade' },
  { id: 'g3', url: '/images/gallery/Image4.jpeg', title: 'Glass Entrance Door', categoryId: 'gcat-glazing' },
  { id: 'g4', url: '/images/gallery/Image5.jpeg', title: 'Red ACP Glass Facade', categoryId: 'gcat-facade' },
  { id: 'g5', url: '/images/gallery/Image6.jpeg', title: 'Red Glass Storefront', categoryId: 'gcat-glazing' },
  { id: 'g6', url: '/images/gallery/Image7.jpeg', title: 'Blue Glass Commercial Building', categoryId: 'gcat-glazing' },
  { id: 'g7', url: '/images/gallery/Image8.jpeg', title: 'Interior Ceiling Finish', categoryId: 'gcat-interiors' },
  { id: 'g8', url: '/images/gallery/Image9.jpeg', title: 'Glass Office Partition', categoryId: 'gcat-interiors' },
]
