export const defaultServices = [
  {
    id: 's1',
    name: 'Façade Systems & Structural Glazing',
    slug: 'facade-systems-structural-glazing',
    shortDescription: 'High-performance curtain walls, spider glazing, and modern exterior architectural glass elevation systems.',
    description: 'We deliver world-class façade engineering, spider glazing, unitized and semi-unitized curtain wall systems engineered for thermal insulation, weather resistance, and stunning visual impact.',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
  {
    id: 's2',
    name: 'Aluminium & Glass Architectural Works',
    slug: 'aluminium-glass-architectural-works',
    shortDescription: 'Premium aluminium doors, windows, partitions, and structural glass railings for commercial and residential buildings.',
    description: 'Specialized fabrication and installation of anodized and powder-coated aluminium section frames, toughened glass partitions, acoustic windows, and frameless glass balustrades.',
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
  {
    id: 's3',
    name: 'Interior & Exterior Finishing',
    slug: 'interior-exterior-finishing',
    shortDescription: 'End-to-end luxury architectural finishes, gypsum ceilings, drywalls, and customized surface paneling.',
    description: 'Comprehensive interior fit-out solutions, false ceilings, acoustic wall paneling, modular space dividers, and high-end exterior surface finishes crafted to perfection.',
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
  {
    id: 's4',
    name: 'ACP Cladding & Panel Elevation',
    slug: 'acp-cladding-panel-elevation',
    shortDescription: 'Durable Aluminium Composite Panel (ACP) cladding systems for vibrant and modern building exteriors.',
    description: 'Weather-proof, fire-retardant ACP sheet cladding engineered for sleek commercial elevations, corporate headquarter façades, and modern architectural remodels.',
    icon: 'ShieldCheck',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
  {
    id: 's5',
    name: 'Commercial Structural Glazing',
    slug: 'commercial-structural-glazing',
    shortDescription: 'Engineered glass curtain walls for IT parks, shopping malls, corporate towers, and showrooms.',
    description: 'Tailored commercial glazing solutions using high-grade solar control glass, laminated security glass, and heavy-duty structural silicones for safety and longevity.',
    icon: 'Building',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
  {
    id: 's6',
    name: 'Customized Construction Solutions',
    slug: 'customized-construction-solutions',
    shortDescription: 'Turnkey architectural metal works, skylights, canopies, and specialized finishing solutions.',
    description: 'Custom steel framing, structural glass skylights, entrance canopies, and bespoke architectural metal features built to exacting client specifications.',
    icon: 'Gem',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    active: true,
  },
]

export const defaultProjects = [
  {
    id: 'p1',
    name: 'Apex Commercial Tower Façade',
    slug: 'apex-commercial-tower-facade',
    location: 'Hyderabad, Telangana',
    clientName: 'Apex Realty Group',
    completionDate: 'January 2025',
    shortDescription: '18-Story unitized glass curtain wall and dynamic LED integrated aluminium façade cladding.',
    fullDescription: 'SV Infra Projects delivered an iconic exterior elevation featuring high-performance low-E structural glazing, integrated spider fittings, and weather-sealed aluminium composite cladding across 120,000 sq.ft.',
    coverImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-facade',
    categoryName: 'Façade Systems & Glazing',
    featured: true,
    active: true,
  },
  {
    id: 'p2',
    name: 'Grand IT Park Structural Glazing',
    slug: 'grand-it-park-structural-glazing',
    location: 'Visakhapatnam, Andhra Pradesh',
    clientName: 'Grand Tech Infrastructure',
    completionDate: 'November 2024',
    shortDescription: 'Double-glazed thermal insulated exterior elevation with frameless glass entry canopy.',
    fullDescription: 'Custom acoustic glazing installation reducing noise transfer by 42dB while providing maximum modern daylighting for a 500,000 sq.ft IT campus.',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-facade',
    categoryName: 'Façade Systems & Glazing',
    featured: true,
    active: true,
  },
  {
    id: 'p3',
    name: 'Luxury Residential Villa Glazing',
    slug: 'luxury-residential-villa-glazing',
    location: 'Jubilee Hills, Hyderabad',
    clientName: 'Private Residence',
    completionDate: 'February 2025',
    shortDescription: 'Floor-to-ceiling slimline aluminium sliding doors and frameless glass balcony railings.',
    fullDescription: 'Ultra-slim profile aluminium sliding doors with motorized shades and toughened laminated safety glass balustrades for a luxury 4-story villa.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-residential',
    categoryName: 'Residential Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p4',
    name: 'Metro Retail Mall Frontage',
    slug: 'metro-retail-mall-frontage',
    location: 'Vijayawada, Andhra Pradesh',
    clientName: 'Metro Mall Developers',
    completionDate: 'December 2024',
    shortDescription: 'Custom ACP metallic panel cladding with spider glass showroom fronts.',
    fullDescription: 'Vibrant exterior elevation transformation incorporating fire-rated ACP panels, clear toughened glass displays, and customized architectural signage supports.',
    coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-commercial',
    categoryName: 'Commercial Projects',
    featured: true,
    active: true,
  },
  {
    id: 'p5',
    name: 'Corporate HQ Glass Partitioning',
    slug: 'corporate-hq-glass-partitioning',
    location: 'Gachibowli, Hyderabad',
    clientName: 'Vanguard Global',
    completionDate: 'March 2025',
    shortDescription: 'Modular acoustic office partitions, glass doors, and luxury interior panelling.',
    fullDescription: 'Complete interior architectural fitting including frameless glass meeting rooms, smart frosted switchable privacy glass, and acoustic ceiling panels.',
    coverImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-interior',
    categoryName: 'Interior Solutions',
    featured: true,
    active: true,
  },
  {
    id: 'p6',
    name: 'Seaside Hotel Glazing & ACP',
    slug: 'seaside-hotel-glazing-acp',
    location: 'Visakhapatnam, AP',
    clientName: 'Oceania Resorts',
    completionDate: 'January 2025',
    shortDescription: 'Corrosion-resistant anodized aluminium windows and coastal-grade ACP paneling.',
    fullDescription: 'Marine-grade weather sealant and anti-salt anodized aluminium glazing systems engineered for high coastal wind pressure and aesthetic brilliance.',
    coverImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=80',
    categoryId: 'cat-aluminium',
    categoryName: 'Aluminium & Glass Works',
    featured: true,
    active: true,
  },
]

export const defaultHeroSlides = [
  {
    id: 'h1',
    title: 'Architectural Glazing & Façade Excellence',
    subheading: 'Engineered for Durability, Aesthetic Perfection, and Energy Efficiency',
    buttonText: 'Explore Projects',
    buttonLink: '/projects',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
  {
    id: 'h2',
    title: 'Modern Aluminium & Glass Solutions',
    subheading: 'Premium Structural Glazing, ACP Cladding, and Customized Finishing',
    buttonText: 'Our Services',
    buttonLink: '/services',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
  {
    id: 'h3',
    title: 'Turnkey Commercial & Residential Fit-Outs',
    subheading: 'Delivering High-Quality Architectural Finishing Across AP & Telangana',
    buttonText: 'Get Free Quote',
    buttonLink: '/contact',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    active: true,
  },
]

export const defaultTestimonials = [
  {
    id: 't1',
    customerName: 'Rajesh Reddy',
    location: 'Hyderabad',
    rating: 5,
    review: 'SV Infra Projects completed our office building façade glazing ahead of schedule. The quality of aluminium sections and glass fitting is top notch!',
    status: 'approved',
  },
  {
    id: 't2',
    customerName: 'K. Suresh Kumar',
    location: 'Visakhapatnam',
    rating: 5,
    review: 'Outstanding professionalism. Their team handled our villa glazing and ACP cladding with extreme precision and premium materials.',
    status: 'approved',
  },
  {
    id: 't3',
    customerName: 'Priya Sharma',
    location: 'Vijayawada',
    rating: 5,
    review: 'Very reliable team for interior glass partitioning and customized finishing. Prompt communication and excellent post-installation support.',
    status: 'approved',
  },
]

export const defaultGallery = [
  { id: 'g1', url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80', title: 'Façade Glazing' },
  { id: 'g2', url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80', title: 'Commercial Glazing' },
  { id: 'g3', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80', title: 'Interior Finishes' },
  { id: 'g4', url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80', title: 'ACP Elevation' },
  { id: 'g5', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80', title: 'Glass Partitions' },
  { id: 'g6', url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80', title: 'Architectural Metal Works' },
]
